#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 20 09:52:15 2020
@author: Kimeunna
"""
# tmp = {'filename1':{'poly1':{'coord_x':[],'coord_y':[]}, 'poly2':{}....}, 'filename2':{}, 'filename3': {}}
import os
import glob

os.chdir("/Users/Kimeunna/Dropbox/아론티어/2020-08-30 he_additional")
files=glob.glob('annotation_txt/*.txt')

tmp = {}
xylist = []
i = 0
coord_x = []
coord_y = []

for file in files:
    with open(file, 'r', encoding='UTF-8') as f:
        for row in f:
            if '/Volumes' in row:
                surgname, _ = os.path.splitext(os.path.basename(row))
                tmp['filename_{}'.format(surgname)] = {}
                j = 0
                continue
            elif '[Point:' in row: # pentagon level 이면
                xy = row.split(', Point:')
                num_poly = int(len(xy))
                xy[0] = (xy[0].lstrip('[Point: '))
                xy[-1] = xy[-1].strip()
                xy[-1] = xy[-1].rstrip(']')
                for xystring in xy:
                    xloc = int(round(float(xystring.split(',')[0])))
                    yloc = int(round(float(xystring.split(',')[1])))
                    coord_x.append(xloc)
                    coord_y.append(yloc)
                tmp['filename_{}'.format(surgname)]['poly_{}'.format(j)] = {'coord_x': coord_x, 'coord_y': coord_y}
                j = j + 1
                coord_x = []
                coord_y = []
                continue

    i = i + 1

print(tmp)
print(tmp['filename_2019S 031805001010']['poly_5']['coord_x'])
