#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 20 09:52:15 2020
@author: Kimeunna
"""
# folder 안의 file list 를 csv 로
import os
import pandas as pd
import numpy as np
import glob

os.chdir("/Users/Kimeunna/Dropbox/아론티어/2020-08-30 he_additional")
files=glob.glob('annotation_txt/*.txt')
print(files)

for file in files:
    f = open(file, 'r', encoding='UTF-8')
    xylist = []
    xyrowlist = []  # polygon 좌표 list
    i = 0
    for row in f:
        if '/Volumes' in row:
            wsi_path = row
            continue
        elif '[Point:' in row:
            xy = row.split(', Point:')
            xy[0] = (xy[0].lstrip('[Point: '))
            xy[-1] = xy[-1].strip()
            xy[-1] = xy[-1].rstrip(']')
            for xystring in xy:
                xloc = int(round(float(xystring.split(',')[0])))
                yloc = int(round(float(xystring.split(',')[1]) / 100))
                xyloc = [xloc, yloc]
                xylist.append(xyloc)
            xyrowlist.append(xylist)
            i = + 1
            xylist = []
    xyrowlist_np = np.array(xyrowlist)
    print(wsi_path)
    print(xyrowlist_np)
    print("===")
